name: Push builds

on:
  push:
    branches:
      - main

jobs:
  build-web:
    uses: ./.github/workflows/build-game.yml
    with:
      platform: HTML5
      name: unknown-car-game
      output_name: index.html
  build-android-debug:
    uses: ./.github/workflows/build-game.yml
    with:
      platform: Android
      name: unknown-car-game
      output_name: UnknownCarGame.apk
      debug: true